version: '3.8'

services:

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - network

  mysql:
    image: mysql:8.0
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}  #required
    ports:
        - ${MYSQL_PORT:-3306}:3306
    expose:
        - 3306
    volumes:
        - ../../symfony5-sandbox/.var/mysql/data:/var/lib/mysql
    networks:
        - network

  fpm:
    build: ./containers/fpm
    depends_on:
      - mysql
    environment:
      - SSH_AUTH_SOCK="${SSH_AUTH_SOCK}"
      - PHP_IDE_CONFIG=serverName=symfony5-sandbox.com # For CLI debuging from container. NO double quotes in value!
    volumes:
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
      - ../../symfony5-sandbox/app:/var/www/symfony5-sandbox
      - ../../symfony5-sandbox/.var/logs/fpm:/var/log
      - ${HOME}/.composer/cache:/root/.composer/cache
      - ${HOME}/.composer/auth.json:/root/.composer/auth.json
    networks:
      - network

  nginx:
    build: ./containers/nginx
    depends_on:
      - fpm
    volumes:
        - ../../symfony5-sandbox/app:/var/www/symfony5-sandbox
        - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./containers/nginx/sites/:/etc/nginx/sites-available
        - ../../symfony5-sandbox/.var/logs/nginx:/var/log/nginx
    ports:
      - ${DOCKER_NGINX_PORT:-80}:80
    networks:
      - network

networks:
  network:
